Strip out redundant instructions from finalize

diff --git a/bin/finalize b/bin/finalize
--- a/bin/finalize
+++ b/bin/finalize
@@ -2,105 +2,56 @@
 
 BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
-ENV_DIR=${3:-}
-BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
+# ENV_DIR=${3:-}   At the moment, we don't need this argument value...
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Rust Build Settings
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-# Set defaults for our configuration variables.
 VERSION=stable
 
-# Setting RUST_SKIP_BUILD to "1" in `RustConfig` installs the Rust toolchain but does not build `Cargo.toml`.
-# This is useful for projects written in other languages (Ruby, Pythoin or NodeJS etc.) that need to build Rust
-# extension modules.
-RUST_SKIP_BUILD=0
+# Import the toolchain configuration if present
+if [ -f "$BUILD_DIR/rust-toolchain" ]
+then
+  VERSION="$(cat "$BUILD_DIR/rust-toolchain")"
+fi
 
 # If your Rust code is not at the root directory of the repository, specify a
 # `BUILD_PATH` to the correct directory in the `RustConfig`
 BUILD_PATH=""
 
 # Default build flags to pass to `cargo build`.
-RUST_CARGO_BUILD_FLAGS="--release"
+RUST_CARGO_BUILD_PROFILE="release"
+RUST_CARGO_BUILD_FLAGS=""
 
-# Load our toolchain configuration, if any was specified.
-if [ -f "$BUILD_DIR/rust-toolchain" ]
-then
-  VERSION="$(cat "$BUILD_DIR/rust-toolchain")"
-fi
-
-# Load our configuration variables, if any were specified.
+# Import any cargo specific environment variables if present
 if [ -f "$BUILD_DIR/RustConfig" ]
 then
   . "$BUILD_DIR/RustConfig"
 fi
 
-# Standard paranoia.
+# Throw toys out of pram if any command fails or a variable is unset
 set -eu
 
 # Check our configuration options.
 if [ -z ${VERSION+x} ]
 then
-  >&2 echo "failed: Must set VERSION in rust-toolchain or RustConfig to indicate the Rust version."
+  >&2 echo "failed: Value for Rust VERSION missing or empty.  Correct this setting in either the rust-toolchain or the RustConfig file"
   exit 1
 fi
-
-# Notify users running old, unstable versions of Rust about how to deploy successfully.
-if [ $RUST_SKIP_BUILD -ne 1  ] &&
-   {
-     [ -n "${CARGO_URL+x}" ] ||
-     [ ! -f "$BUILD_DIR/$BUILD_PATH/Cargo.toml" ];
-   }
-then
-  >&2 cat <<EOF
-To deploy a modern Rust app, make sure you have a Cargo.toml file, and that
-you do not define CARGO_URL or CARGO_VERSION in RustConfig.  If you're
-using an older version of Rust, and you need to re-deploy an existing
-application, try setting your buildpack to:
-
-  https://github.com/emk/heroku-buildpack-rust.git#old-rust
-EOF
-  exit 1
-fi
-
-# Record our Rust build environment configuration in an export file, in case another buildpack needs it to build
-# something like Ruby gems etc.
-cat <<EOF > "$BP_DIR/export"
-# Our rustup installation.
-export RUSTUP_HOME="$CACHE_DIR/multirust"
-
-# Our cargo installation.  We implicitly trust Rustup and Cargo
-# to do the right thing when new versions are released.
-export CARGO_HOME="$CACHE_DIR/cargo"
-
-# Include binaries installed by cargo and rustup in our path.
-PATH="\$CARGO_HOME/bin:\$PATH"
-EOF
-
-# Read our build environment back in and evaluate it so that we can use it.
-. $BP_DIR/export
 
 # Switch to our cache directory.
 mkdir -p "$CACHE_DIR"
 cd "$CACHE_DIR"
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Make sure build tools are up to date
+# TODO: Since we're using the standard rust image, is this entirely necessary?
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
 # Make sure we have an appropriate Rust toolchain installed.
-if [ -d "$CARGO_HOME" ]
-then
-  echo "-----> Checking for new releases of Rust $VERSION channel"
-  # It's possible that $VERSION has changed, or the `stable` channel has updated.
-  rustup self update
-  rustup update "$VERSION"
-  rustup default "$VERSION"
-else
-  echo "-----> Downloading rustup"
-  curl https://sh.rustup.rs -sSf > rustup.sh
-  chmod u+x rustup.sh
-  echo "-----> Using rustup to install Rust channel $VERSION"
-  ./rustup.sh -y --default-toolchain "$VERSION"
-  rm rustup.sh
-fi
+rustup self update
+rustup update "$VERSION"
+rustup default "$VERSION"
 
 if [ ! -x "$CARGO_HOME/bin/rustc" ]
 then
@@ -108,27 +59,24 @@ then
   exit 1
 fi
 
-# This is where we will cache our Rust output.  Note the suggestions at
-# https://github.com/alexcrichton/cargo/commit/014765f788ca1c2476936835ca32cc2746f99b42
-# which describe how this needs to be named.
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+# Start build process
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+# Direct the Rust compiler output to the cache
 export CARGO_TARGET_DIR="$CACHE_DIR/target"
 
-if [ $RUST_SKIP_BUILD -ne 1 ]
+# Build the project then copy the binary from the cache back to the source tree.
+echo "-----> Building application using Cargo"
+cd "$BUILD_DIR/$BUILD_PATH"
+rm -rf target/
+
+if [ -z "${RUST_CARGO_BUILD_FLAGS}" ]
 then
-  # Build our project (into CARGO_TARGET_DIR so we have caching) and copy it back to the source tree.
-  # In theory, we could probably just copy the binary or do something clever with `cargo install`, but we haven't
-  # figured that out yet.
-  #
-  # To debug git issues:
-  # export RUST_LOG="cargo::sources::git=debug"
-  #
-  # To debug compiler and linking issues, add `--verbose`.
-  echo "-----> Building application using Cargo"
-  cd "$BUILD_DIR/$BUILD_PATH"
-  rm -rf target/
-  cargo build $RUST_CARGO_BUILD_FLAGS
-  mkdir -p target/release
-  find "$CARGO_TARGET_DIR/release" -maxdepth 1 -type f -executable -exec cp -a -t target/release {} \;
+  cargo build --"$RUST_CARGO_BUILD_PROFILE"
 else
-  echo "-----> RUST_SKIP_BUILD switched on: Skipping Cargo build"
+  cargo build --"$RUST_CARGO_BUILD_PROFILE" "$RUST_CARGO_BUILD_FLAGS"
 fi
+
+mkdir -p target/"$RUST_CARGO_BUILD_PROFILE"
+find "$CARGO_TARGET_DIR/$RUST_CARGO_BUILD_PROFILE" -maxdepth 1 -type f -executable -exec cp -a -t target/"$RUST_CARGO_BUILD_PROFILE" {} \;
