Test failed build

diff --git a/bin/supply b/bin/supply
--- a/bin/supply
+++ b/bin/supply
@@ -2,6 +2,7 @@
 # usage: bin/supply <build-dir> <cache-dir> <env-dir>
 
 echo "-----> Start supply"
+CONFIG_FILE=RustToolchain
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Install/Update Rust toolchain
@@ -9,22 +10,22 @@ echo "-----> Start supply"
 VERSION=stable
 
 # Import the toolchain configuration if present
-if [ -f "$BUILD_DIR/rust-toolchain" ]
+if [ -f "$BUILD_DIR/$CONFIG_FILE" ]
 then
-  VERSION="$(cat "$BUILD_DIR/rust-toolchain")"
+  VERSION="$(cat "$BUILD_DIR/$CONFIG_FILE")"
 fi
 
 # Check our configuration options.
 if [ -z ${VERSION+x} ]
 then
-  >&2 echo "failed: Value for Rust VERSION missing or empty.  Use the 'rust-toolchain' file to define a non-default value or delete this file to use the default 'stable' channel"
+  >&2 printf "failed: Rust VERSION is empty.\nTo use a version other than the Rust stable channel, add the desired version or 'nightly' to the file %s" $CONFIG_FILE
   exit 1
 fi
 
 if command -v rustup &> /dev/null
 then
+  # It's possible that $VERSION has changed or been updated since Rust was installed in this container
   echo "-----> Checking for new releases of Rust $VERSION channel"
-  # It's possible that $VERSION has changed, or the `stable` channel has been updated.
   rustup self update
   rustup update "$VERSION"
   rustup default "$VERSION"
@@ -32,7 +33,7 @@ else
   echo "-----> Downloading rustup"
   curl https://sh.rustup.rs -sSf > rustup.sh
   chmod u+x rustup.sh
-  echo "-----> Using rustup to install Rust $VERSION channel"
+  echo "-----> Install Rust $VERSION channel"
   ./rustup.sh -y --default-toolchain "$VERSION"
   rm rustup.sh
 fi
